export const IP_PORT = "http://127.0.0.1:8000/"
export const LOST_AND_FOUND = "lostandfound/"
export const GET_USER_LOST_ITEMS = "get-user-lost-items"
export const GET_MATCHED_FOUND_ITEMS = "get-matched-found-items"
export const DELETE_ITEM = "delete-item"